on:
  workflow_call:
    inputs:
      ENV:
        type: string
        description: Environment code
        required: false

name: ENV - Poc

jobs:
  test:
    name: ENV PoC
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: ENV PoC
        if: github.ref == 'refs/heads/test'
        run: |
          echo $GITHUB_REF
          echo ${{ inputs.ENV }}
          curl -X GET "https://api.nucleus.bet/${{ inputs.ENV }}"

      - name: ENV PoC 2
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X GET "https://api.nucleus.bet/sport_filter"